# Generated by Django 4.0.6 on 2022-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='direct_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
